### ISSUE TITLE
Ensure duplicate points are allowed everywhere (CSV/CPC import, spacer interfacing)

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#308] opened 2020-04-05 09:06 UTC
2020/05 update - tasks agreed upon:

- [x] Allow duplicate points in CSV/CPC import. (Done in PR #320)
- [x] Ensure spacer interfacing works with duplicate points.

-----

(Original issue name: Should duplicate points on an image be disallowed or mitigated?)

'Duplicate' meaning points with the same row, column values on the same image. There's nothing in the current point-generation code that disallows this. It also doesn't retry point generation if dupes are detected.

We have a few possible paths:

1. Leave the code as is.

2. Strictly disallow duplicate points. This can actually be a pain to implement, because in the odd case that there are more points than pixels, we have to report an error to the user somehow. Also, I believe we basically have an invariant that every image has points at all times, and breaking this invariant could cause other kinds of trouble.

3. Mitigation version A: After generating point locations for an image, if any duplicates are found among them, try generating all the points again. Retry a maximum of N times (perhaps N = 10) as long as duplicates remain. If after N times, we still have duplicates, then just keep the duplicates. This may or may not be considered bad random-sampling practice by some people.

4. Mitigation version B: After generating one point location, if it's a duplicate of a point location we generated previously for this image, try generating that one point again. Retry a maximum of N times (perhaps N = 10) as long as we still have a duplicate, before moving onto the next point. This will probably be considered bad random-sampling practice by some people.

We could also implement 2, 3, or 4 but make it optional, perhaps a source-level setting.

My guess is that implementing 3 as optional would be the best course of action, but I'm also not sure if it's much of a priority.

**Comment by beijbom** [comment] 2020-04-06 02:27
My vote is for option 4. I'm not a expert stats person, but I'm pretty sure that is OK. It's just an implementation of sampling without replacement.

**Comment by kriegman** [comment] 2020-04-06 03:43
So, the number of pairs that can be in duplicates grows as O(n^2), actually
n(n+1)/2 pairs, which can get to be reasonably probably when the number of
points is large (or imge size is small). Maybe not that frequent for 200
points and a 1 Mpixel image.

Anyway, I'd go with #4 because the chance of drawing a second duplicate is
pretty slim. Only if someone tries to basically densely sample with random
samples are they screwed...and they deserve to be ;)

David

**Comment by StephenChan** [comment] 2020-04-06 19:22
Yeah, I'm even less of a stats person, so option 4 sounds good. Should it be an optional thing, or should we just always do sampling without replacement?

Using the 'birthday problem' formula in Python, I got a 2% collision chance for 200 points in a 1 megapixel image:

```python
>>> from decimal import Decimal as D
>>> from functools import reduce
>>> import operator
>>> 1 - reduce(operator.mul, [D(1) - (D(i) / D(1000000)) for i in range(1, 200)], 1)
Decimal('0.0197045993289520605100990972')
```

More collision probabilities for reference:

- 100 points in 1 megapixel: 0.5%
- 100 points in 10 megapixels: 0.05%
- 50 points in 10 megapixels: 0.012%
- 20 points in 10 megapixels: 0.0019%

So in real-world examples, duplicates won't be too rare, but they won't be found in every other image, either.

-----

Coding note for myself: the following lines

```python
row = random.randint(annoarea_min_row, annoarea_max_row)
column = random.randint(annoarea_min_col, annoarea_max_col)
```

would be replaced with something like this, where `points_so_far` is a set:

```python
for _ in range(10):
    row = random.randint(annoarea_min_row, annoarea_max_row)
    column = random.randint(annoarea_min_col, annoarea_max_col)
    if (row, column) not in points_so_far:
        break
points_so_far.add((row, column))
```

**Comment by beijbom** [comment] 2020-04-10 15:25
@StephenChan : yeah. I like this a lot. Are you thinking we will go back and remove old identical (row, col) points? Probably not, huh, since that would mess up previous analysis. (if we add new (row,, col) locations to images all over the place, those images will not be "confirmed" anymore, which would be a bit of a nightmare. ) 

I'm just bringing it up since we'd still have to make sure the downstream code can handle identical (row, col) locations. Which I suppose I obvious, since even this schema could result in identical (row, col) values if all 10 trials fail.

**Comment by StephenChan** [comment] 2020-04-10 19:07
> yeah. I like this a lot. Are you thinking we will go back and remove old identical (row, col) points? Probably not, huh, since that would mess up previous analysis. (if we add new (row,, col) locations to images all over the place, those images will not be "confirmed" anymore, which would be a bit of a nightmare. )

Yeah, I wasn't planning on that. This is just to make future analyses a bit tidier.

> I'm just bringing it up since we'd still have to make sure the downstream code can handle identical (row, col) locations. Which I suppose I obvious, since even this schema could result in identical (row, col) values if all 10 trials fail.

Correct.

**Comment by StephenChan** [comment] 2020-05-04 08:03
I just noticed a related thing which is kind of silly. Back when I created the Upload Annotations forms, I made it deny the upload if multiple points are on the same row and column. This applies to both CSV and CPC uploads.

So it is possible to generate duplicate points, export those points, and then not be able to import them back into CoralNet. That doesn't seem right to me. I guess upload should just issue a warning if dupe points are detected, rather than denying the upload.

And one other thought: I should check whether the CPCe software complains about dupe points.

**Comment by beijbom** [comment] 2020-05-05 03:51
@StephenChan : have you crawled the current data-base to see how many dupes we have currently? I'm tempted to say we should simply not allow duplicates. Here is how it could work:
- For existing duplicates, we move one of the points 1 row or 1 column. So it'd be right next to its original location. With such small movement we can simply keep the old annotations. We could also publish a list of affected sources & images if ppl wanted to double check.
- For new images, we can run the same algorithm that you described here (option 4), but if it fails after 10 iterations, we just move the point over 1 row or 1 column.
- For imported annotations we check for and do not allow duplicates.

I know moving points is a bit hacky, but the benefits would be quite large in terms of downstream processing and logic. In particular the spacer integration would be cleaner, but I suspect stuff like annotation tool and other things would benefit also.

Also: given our other discussion about the current confusion re. 0 or 1 indexing, it appears to me that moving points 1 row/column over should be fine since we have been a little cavalier about this anyways. So in a way we can straighten both these little things out in one sweep.

**Comment by StephenChan** [comment] 2020-05-05 05:16
> have you crawled the current data-base to see how many dupes we have currently?

Not yet. I think I'll check this before replying in more detail.

**Comment by StephenChan** [comment] 2020-05-09 05:03
> have you crawled the current data-base to see how many dupes we have currently?

There are 5608 images with dupe points, spanning 147 sources.

- 5119 of the images have multiple dupes; 489 have only 1 dupe.

- 4988 of the images span 7 sources, and these sources set 1-pixel annotation areas for most of their images (e.g. X: 10 - 10% / Y: 5 - 5%).

- 250 of the images (spanning 88 sources) are human annotated. 86 of the images (spanning 14 sources) had points imported, presumably before the import code started checking for dupes.

- Some images with dupes have really small resolutions (like 512 pixels on a side), somewhat small ones (1398 x 1398, 100 points), annotation areas restricted to one dimension (X: 10 - 10% / Y: 10 - 95%), or just seem to be unlucky (4000 x 3000, 30 points).

I can email you a CSV with more details.

> I'm tempted to say we should simply not allow duplicates. Here is how it could work:
>
> - For existing duplicates, we move one of the points 1 row or 1 column. So it'd be right next to its original location. With such small movement we can simply keep the old annotations. We could also publish a list of affected sources & images if ppl wanted to double check.
> - For new images, we can run the same algorithm that you described here (option 4), but if it fails after 10 iterations, we just move the point over 1 row or 1 column.
> - For imported annotations we check for and do not allow duplicates.

But moving by 1 pixel may just give us a different duplicate. Especially for new images, because if it fails after 10 iterations, the annotation area is probably just really small.

So to address point generation for new images, I'd like to walk back something I said in my original post. It really should be quite reasonable to implement point-generation error messages:

- If point-gen fails during an image upload, then we make the image upload fail without saving anything (similar to getting a corrupt image).

- If point-gen fails when resetting the annotation area to source default, then we don't save the area reset and show an appropriate error message (perhaps advising that the area is too small for the number of points).

And so on. At the same time, if possible, I actually think we should allow importing dupe points. But it would come with a warning message on the import-preview. And dupes would only be allowed via import, not by generation within CoralNet. Basically, making dupes would take effort, but still be possible. A few thoughts behind this:

- Most people probably won't want dupes. However, some people do still hope to import data from old projects without doing too much pre-processing. Also, sampling with replacement isn't an invalid statistical method.

- I checked CPCe's behavior, and it has no qualms with assigning two points to the same pixel. The fact that CPCe uses 1/15ths of pixels helps, but it's even OK with letting two points be on the same 1/15th. So a no-dupe policy could increase the friction on importing studies that were started with CPCe (or for that matter, any other point-sampling software that might allow dupes). To be fair, I don't recall us getting complaints about this, but you'll note that we do have some imported dupes from years back.

- Yeah, dupes do look silly as point overlays in the annotation tool. But it can be mitigated somewhat by toggling the view to only show selected points, and then selecting the desired point via the points list. Or just rectangle-select both points and label them together. I think that's good enough if dupes are considered a fringe case.

- I don't have much opinion on the deploy API's dupe policy, since the API client already needs to do some data pre-processing work to craft the requests.

> I know moving points is a bit hacky, but the benefits would be quite large in terms of downstream processing and logic. In particular the spacer integration would be cleaner, but I suspect stuff like annotation tool and other things would benefit also.

I honestly can't think of any potential issues with dupes within CoralNet. I believe CoralNet always identifies points by point number or database ID rather than row/col. So, CoralNet shouldn't particularly care about two points having the same row/col, if we don't consider spacer interfacing.

However, I do see the issue with the spacer interfacing. Particularly how spacer's `ImageFeatures` class has a hash indexed by (row, col) tuples. If CoralNet can have dupe points, and spacer cannot, then we'll have to be careful when passing rowcol lists, traindata/valdata, etc. between the two. And maybe having to still support Beta 1 features etc. would make things more complicated.

Still, if the alternative is to do more data alterations on existing sources, I'd want to be more convinced that dupes are really more trouble than they're worth.

@beijbom How does this idea sound: you can first write the `vision_backend` spacer integration without considering dupe points at all. Then I can see how hard it is to modify the `vision_backend` code to accommodate dupes. To be clear, my goal would be to have the interfacing burden be entirely on CoralNet, without inconveniencing the spacer code.

> Also: given our other discussion about the current confusion re. 0 or 1 indexing, it appears to me that moving points 1 row/column over should be fine since we have been a little cavalier about this anyways. So in a way we can straighten both these little things out in one sweep.

The above points notwithstanding, I suppose the part about cavalier-ness is fair. But if the conclusion is that dupes aren't worth it, I'd actually hope we can just delete the existing duplicate points (without generating new points) instead of moving them. Deleting dupes is less hacky and guaranteed to work for all the dupe point cases, even if the annotation area is just 1 pixel wide.

**Comment by kriegman** [comment] 2020-05-09 05:46
OK. So this point is interesting:
4988 of the images span 7 sources, and these sources set 1-pixel annotation
areas for most of their images (e.g. X: 10 - 10% / Y: 5 - 5%).

which is 90% of dupes. If I understand this correctly, all the points are
being assigned to one pixel? And the user set up the annotation area to
only be
one pixel. It seems likely the users made a mistake in setting up the
annotation area, and it might be an indication that they didn't understand
the UI or what they were supposed to be doing.  It seems like these
could be prevented by not allowing these really small annotation areas or
asking question: "Are you sure you only want to annotate 0.0001% of the
image? This isn't so much removing dupes but preventing user error and
creating a better user experience.

**Comment by StephenChan** [comment] 2020-05-09 08:29
Yes, those are annotation areas of one pixel. Agreed that those cases are almost certainly from misunderstanding the annotation area fields.

If we do raise a point-generation error (as I suggested) when the '10 tries' algorithm fails to make unique points, that will probably catch the most extreme cases of tiny annotation areas - certainly this 1-pixel case, and any other case where the point count exceeds or is close to the pixel count.

Beyond that, I suppose we can display a warning if the area is below, say, 5% of the entire image. Or work on making the annotation area more intuitive to set (we've had a few ideas over the years including issue #91).

**Comment by beijbom** [comment] 2020-05-09 22:35
@StephenChan : thanks for looking into this. Very interesting to see where these dupes come from.

After reading through your post, and also the one related to 0 vs 1 indexing, I agree with your conclusion that we should allow dupes. Part of my motivation was a deeper feeling of wanting simplicity everywhere as much as possible, to avoid misc errors down the road. But this seems like a situation where we can accept the extra complexity row-col dupes bring. As per spacer, I have a pretty clear idea of how to handle it. I don't think it will add that many lines of code. Let's see how it plays out.

So to summarize, it seems there are two options on the table.
- Allow existing dupes, allow dupes to be imported, and allow dupes to be generated by us.
- Allow existing dupes, allow dupes to be imported, do not allow dupes to be generated by us.

Between these, I'd vote for the first one. If we accept the extra complexity of allowing dupes let's leave the random point generation as clean as possible. Also, if CPC allows it there may be a good stats reason for it (and by extension, most users may want it).  

That being said, we should probably elevate https://github.com/beijbom/coralnet/issues/91 to at least alert the users who set the annotation area super-small erroneously since that alone would eliminate 90% of future dupes.

**Comment by StephenChan** [comment] 2020-05-10 08:29
> After reading through your post, and also the one related to 0 vs 1 indexing, I agree with your conclusion that we should allow dupes. Part of my motivation was a deeper feeling of wanting simplicity everywhere as much as possible, to avoid misc errors down the road. But this seems like a situation where we can accept the extra complexity row-col dupes bring. As per spacer, I have a pretty clear idea of how to handle it. I don't think it will add that many lines of code. Let's see how it plays out.

Ok, that would be great.

> So to summarize, it seems there are two options on the table.
> 
>     * Allow existing dupes, allow dupes to be imported, and allow dupes to be generated by us.
> 
>     * Allow existing dupes, allow dupes to be imported, do not allow dupes to be generated by us.
> 
> 
> Between these, I'd vote for the first one. If we accept the extra complexity of allowing dupes let's leave the random point generation as clean as possible.

Fair point. I'm fine with either way here, and certainly the easier thing to do is option 1, i.e. leave point generation as is.

> Also, if CPC allows it there may be a good stats reason for it (and by extension, most users may want it).

Honestly not sure here, though. This goes back to one of the initial questions in this issue: do people generally go for sampling with replacement, sampling without replacement, or should we give a choice? It may be worth asking around. Though if we haven't gotten any requests of this nature, then it's not as big of a priority as some other tasks.

> That being said, we should probably elevate #91 to at least alert the users who set the annotation area super-small erroneously since that alone would eliminate 90% of future dupes.

I suppose we can create a separate issue for that simple warning. But I've elevated #91 from Beta 4 to Beta 3 at any rate.

**Comment by beijbom** [comment] 2020-05-10 15:32
Re. sampling with replacement vs. sampling without replacement: I agree: Let's shelve if for now until a user actually shows they care about it.

Re. #91 : Sounds good. Yeah, just displaying the percent image area after they select the row, col limits, along with a warning if the area is too small, would probably suffice.

**Comment by StephenChan** [comment] 2020-05-10 19:58
> Re. sampling with replacement vs. sampling without replacement: I agree: Let's shelve if for now until a user actually shows they care about it.

Sounds good. Shelved to issue #316.

> Re. #91 : Sounds good. Yeah, just displaying the percent image area after they select the row, col limits, along with a warning if the area is too small, would probably suffice.

Created #317 for that.

So, tasks remaining for this issue:

- Allow duplicate points in CSV/CPC import. (With a warning, or no?)
- Ensure spacer interfacing works with duplicate points.

**Comment by beijbom** [comment] 2020-12-10 22:23
@StephenChan : I closed this now since both remaining items are complete.

**Closed by beijbom** 2020-12-10 22:23 UTC
Labels: annotation
